export const PROJECTS = [
  {
    slug: "poof",
    name: "POOF",
    cover: "/svgs/06-poof-transfer.svg",
    tagline: "no-friction file sharing",
    desc: "Drop a file, get a link — no sign-up, no friction. Supports multi-file uploads as a single zip link, resumable downloads via HTTP range requests, SHA-256 deduplication, malware scanning via VirusTotal, and automatic 24-hour expiry. Files go directly from your browser to Cloudflare R2 — the server never touches your bytes.",
    tags: ["Next.js", "Vercel", "Cloudflare R2", "D1", "Upstash"],
    status: "live",
    live: "https://poof-file-sharing.vercel.app/",
    gh: "https://github.com/shyamsinghnegi/POOF-File-sharing",
    slot: "a",
    screenshots: [
      { src: "/project-images/poof/Home_page.jpg", alt: "POOF home page" },
      { src: "/project-images/poof/Upload_page.jpg", alt: "POOF upload page" },
      { src: "/project-images/poof/Download_page.jpg", alt: "POOF download page" },
    ],
    stack: [
      { layer: "Frontend", tech: "Next.js + Vercel" },
      { layer: "Storage", tech: "Cloudflare R2" },
      { layer: "Metadata / DB", tech: "Cloudflare D1" },
      { layer: "Rate limiting", tech: "Upstash Redis" },
    ],
    features: [
      { title: "Direct-to-storage uploads", body: "Files stream straight from the browser to Cloudflare R2 via signed URLs — the server never buffers or touches file bytes." },
      { title: "Multi-file zip links", body: "Multiple files in one drop are bundled and shared as a single link, generated on the fly." },
      { title: "Resumable downloads", body: "HTTP range requests let large downloads resume after a dropped connection instead of restarting." },
      { title: "Automatic expiry", body: "Every upload is deleted after 24 hours by default, so nothing lingers." },
    ],
    getStarted: [
      "Open the live site and drag a file (or a folder) onto the drop zone.",
      "Wait for the SHA-256 dedupe + VirusTotal scan to clear.",
      "Copy the generated link and share it — it self-destructs in 24 hours.",
    ],
  },
  {
    slug: "macrograin",
    name: "MacroGrain",
    cover: "/svgs/07-macrograin-ring.svg",
    tagline: "calorie & macro tracker",
    desc: "A calorie and macro tracker that gets you logging in one tap — scan a barcode, snap a plate, or read a nutrition label — and adapts your daily target from what actually happens to your weight, not a number guessed once at signup.",
    tags: ["Next.js", "TypeScript", "Cloudflare D1", "Drizzle", "Gemini"],
    status: "live",
    live: "https://macro-grain.vercel.app/",
    gh: "https://github.com/shyamsinghnegi/MacroGrain",
    slot: "f",
    screenshotLayout: "mobile",
    screenshots: [
      { src: "/project-images/macrograin/dashboard-top.jpeg", alt: "MacroGrain dashboard" },
      { src: "/project-images/macrograin/scan-capture.jpeg", alt: "MacroGrain AI capture" },
      { src: "/project-images/macrograin/weight.jpeg", alt: "MacroGrain weight tracking" },
      { src: "/project-images/macrograin/settings.jpeg", alt: "MacroGrain settings" },
    ],
    stack: [
      { layer: "Frontend", tech: "Next.js 16 (App Router, Server Components)" },
      { layer: "Database", tech: "Cloudflare D1 via Drizzle ORM" },
      { layer: "Auth", tech: "Auth.js (Google OAuth)" },
      { layer: "AI", tech: "Google Gemini for photo/label recognition" },
      { layer: "Food data", tech: "USDA FoodData Central + Open Food Facts" },
    ],
    features: [
      { title: "AI photo scan", body: "Snap a plate and Gemini estimates food and macros, with the portion editable before saving." },
      { title: "Barcode & label scan", body: "In-browser barcode decoding against Open Food Facts, plus OCR that reads a nutrition facts panel directly." },
      { title: "Adaptive targets", body: "Weekly recalculation backs out your real TDEE from actual intake vs. actual weight change instead of a fixed formula, gated by a confidence threshold (5+ logged days, 3+ weigh-ins) so a sparse week holds the old target rather than drifting it — computed on timezone-correct week boundaries and cached idempotently against concurrent requests." },
      { title: "Real push reminders", body: "Service worker + Web Push deliver reminders even with the app fully closed, with quiet hours computed in your own timezone." },
    ],
    getStarted: [
      "Open the live site and sign in with Google.",
      "Log a meal by photo, barcode, label scan, or manual search.",
      "Check the dashboard for today's calories, macros, and trend.",
    ],
  },
  {
    slug: "floatchat",
    name: "FloatChat",
    cover: "/svgs/08-floatchat-waves.svg",
    tagline: "ocean data in plain language",
    desc: "Query and visualise ARGO ocean data in plain language — a hybrid text-to-SQL and vector-retrieval pipeline over NetCDF datasets flattened into Postgres.",
    tags: ["Python", "LLM", "Postgres", "ChromaDB", "TypeScript"],
    status: "wip",
    gh: "https://github.com/shyamsinghnegi/FloatChat",
    slot: "b",
    screenshots: [
      { alt: "Screenshot 1" },
      { alt: "Screenshot 2" },
      { alt: "Screenshot 3" },
    ],
    stack: [
      { layer: "Data ingestion", tech: "Python, NetCDF (ARGO floats) flattened into Postgres" },
      { layer: "Retrieval", tech: "Hybrid: LLM-generated SQL + ChromaDB vector search for relevant profiles" },
      { layer: "Frontend", tech: "TypeScript" },
    ],
    features: [
      { title: "Plain-language queries", body: "Ask questions about ocean temperature, salinity, and float trajectories without writing SQL or NetCDF queries by hand." },
      { title: "Schema-aware SQL generation", body: "An LLM writes SQL against a schema with a booby-trapped composite key — profile_id is a VARCHAR string, not the numeric cycle_number column users actually mean by \"profiles 5 to 15\" — guarded by schema-aware prompting and a self-correction retry loop that feeds the LLM's own SQL errors back to it." },
      { title: "Query-aware routing", body: "Aggregate questions (\"total\", \"how many\", \"highest\") skip vector retrieval entirely and hit Postgres directly, since top-k profile similarity search answers them wrong." },
    ],
    getStarted: [
      "Clone the repo and follow the setup instructions in the README.",
      "Point it at a local or remote ARGO NetCDF dataset.",
      "Ask a question in plain language and get a grounded answer plus a chart.",
    ],
  },
  {
    slug: "civicrelay",
    name: "CivicRelay",
    cover: "/svgs/09-civicrelay-pin.svg",
    tagline: "civic issue reporting",
    desc: "Report local civic issues with a photo and a pin — the photo is auto-classified into a category before the report is even created.",
    tags: ["Next.js", "Azure AI Vision", "Azure Blob Storage", "Cosmos DB"],
    status: "wip",
    gh: "https://github.com/shyamsinghnegi/CivicRelay",
    slot: "c",
    screenshots: [
      { alt: "Screenshot 1" },
      { alt: "Screenshot 2" },
      { alt: "Screenshot 3" },
    ],
    stack: [
      { layer: "Frontend / API", tech: "Next.js App Router (route handlers, no separate backend)" },
      { layer: "Vision", tech: "Azure AI Vision (image tagging)" },
      { layer: "Storage", tech: "Azure Blob Storage" },
      { layer: "Database", tech: "Azure Cosmos DB" },
    ],
    features: [
      { title: "Photo + location reports", body: "Citizens snap a photo and drop a pin; the location is reverse-geocoded to a place name via Azure Maps." },
      { title: "Auto category classification", body: "Vision tags are scored against a hand-tuned ~90-term civic taxonomy (crack/rut/asphalt → pothole, manhole/culvert → drainage) to classify the issue, with a confidence floor that rejects blurry or off-topic photos before a report is created." },
      { title: "Content-addressed uploads", body: "Photos are hashed (SHA-256) and deduplicated against Blob Storage by that hash, so a retried or resubmitted upload never creates a duplicate blob." },
    ],
    getStarted: [
      "Open the app and allow location access.",
      "Snap a photo of the issue and drop a pin.",
      "Submit — the category is classified automatically from the photo.",
    ],
  },
]
