export const PROJECTS = [
  {
    slug: "poof",
    name: "POOF",
    cover: "/svgs/06-poof-transfer.svg",
    tagline: "no-friction file sharing",
    desc: "Drop a file, get a link — no sign-up, no friction. Supports multi-file uploads as a single zip link, resumable downloads via HTTP range requests, SHA-256 deduplication, malware scanning via VirusTotal, and automatic 24-hour expiry. Files go directly from your browser to Cloudflare R2 — the server never touches your bytes.",
    tags: ["Next.js", "Vercel", "Cloudflare R2", "D1", "Upstash"],
    status: "live",
    live: "https://poof-file-sharing.vercel.app/",
    gh: "https://github.com/shyamsinghnegi/POOF-File-sharing",
    slot: "a",
    screenshots: [
      { src: "/project-images/poof/Home_page.jpg", alt: "POOF home page" },
      { src: "/project-images/poof/Upload_page.jpg", alt: "POOF upload page" },
      { src: "/project-images/poof/Download_page.jpg", alt: "POOF download page" },
    ],
    stack: [
      { layer: "Frontend", tech: "Next.js + Vercel" },
      { layer: "Storage", tech: "Cloudflare R2" },
      { layer: "Metadata / DB", tech: "Cloudflare D1" },
      { layer: "Rate limiting", tech: "Upstash Redis" },
    ],
    features: [
      { title: "Direct-to-storage uploads", body: "Files stream straight from the browser to Cloudflare R2 via signed URLs — the server never buffers or touches file bytes." },
      { title: "Multi-file zip links", body: "Multiple files in one drop are bundled and shared as a single link, generated on the fly." },
      { title: "Resumable downloads", body: "HTTP range requests let large downloads resume after a dropped connection instead of restarting." },
      { title: "Automatic expiry", body: "Every upload is deleted after 24 hours by default, so nothing lingers." },
    ],
    getStarted: [
      "Open the live site and drag a file (or a folder) onto the drop zone.",
      "Wait for the SHA-256 dedupe + VirusTotal scan to clear.",
      "Copy the generated link and share it — it self-destructs in 24 hours.",
    ],
  },
  {
    slug: "macrograin",
    name: "MacroGrain",
    cover: "/svgs/07-macrograin-ring.svg",
    tagline: "calorie & macro tracker",
    desc: "A calorie and macro tracker that gets you logging in one tap — scan a barcode, snap a plate, or read a nutrition label — and adapts your daily target from what actually happens to your weight, not a number guessed once at signup.",
    tags: ["Next.js", "TypeScript", "Cloudflare D1", "Drizzle", "Gemini"],
    status: "live",
    live: "https://macro-grain.vercel.app/",
    gh: "https://github.com/shyamsinghnegi/MacroGrain",
    slot: "f",
    screenshotLayout: "mobile",
    screenshots: [
      { src: "/project-images/macrograin/dashboard-top.jpeg", alt: "MacroGrain dashboard" },
      { src: "/project-images/macrograin/scan-capture.jpeg", alt: "MacroGrain AI capture" },
      { src: "/project-images/macrograin/weight.jpeg", alt: "MacroGrain weight tracking" },
      { src: "/project-images/macrograin/settings.jpeg", alt: "MacroGrain settings" },
    ],
    stack: [
      { layer: "Frontend", tech: "Next.js 16 (App Router, Server Components)" },
      { layer: "Database", tech: "Cloudflare D1 via Drizzle ORM" },
      { layer: "Auth", tech: "Auth.js (Google OAuth)" },
      { layer: "AI", tech: "Google Gemini for photo/label recognition" },
      { layer: "Food data", tech: "USDA FoodData Central + Open Food Facts" },
    ],
    features: [
      { title: "AI photo scan", body: "Snap a plate and Gemini estimates food and macros, with the portion editable before saving." },
      { title: "Barcode & label scan", body: "In-browser barcode decoding against Open Food Facts, plus OCR that reads a nutrition facts panel directly." },
      { title: "Adaptive targets", body: "Weekly recalculation backs out your real TDEE from actual intake vs. actual weight change, instead of relying on a number guessed once at signup." },
      { title: "Real push reminders", body: "Service worker + Web Push deliver reminders even with the app fully closed, with quiet hours computed in your own timezone." },
    ],
    getStarted: [
      "Open the live site and sign in with Google.",
      "Log a meal by photo, barcode, label scan, or manual search.",
      "Check the dashboard for today's calories, macros, and trend.",
    ],
  },
  {
    slug: "floatchat",
    name: "FloatChat",
    cover: "/svgs/08-floatchat-waves.svg",
    tagline: "ocean data in plain language",
    desc: "Query and visualise ARGO ocean data in plain language — RAG pipeline over NetCDF datasets.",
    tags: ["Python", "LLM", "RAG", "TypeScript"],
    status: "wip",
    gh: "https://github.com/shyamsinghnegi/FloatChat",
    slot: "b",
    screenshots: [
      { alt: "Screenshot 1" },
      { alt: "Screenshot 2" },
      { alt: "Screenshot 3" },
    ],
    stack: [
      { layer: "Data ingestion", tech: "Python, NetCDF (ARGO floats)" },
      { layer: "Retrieval", tech: "RAG pipeline over parsed ocean datasets" },
      { layer: "Frontend", tech: "TypeScript" },
    ],
    features: [
      { title: "Plain-language queries", body: "Ask questions about ocean temperature, salinity, and float trajectories without writing NetCDF queries by hand." },
      { title: "RAG over real datasets", body: "Retrieval-augmented generation grounds answers in the actual ARGO float data rather than hallucinating numbers." },
    ],
    getStarted: [
      "Clone the repo and follow the setup instructions in the README.",
      "Point it at a local or remote ARGO NetCDF dataset.",
      "Ask a question in plain language and get a grounded answer plus a chart.",
    ],
  },
  {
    slug: "civicrelay",
    name: "CivicRelay",
    cover: "/svgs/09-civicrelay-pin.svg",
    tagline: "civic issue reporting",
    desc: "Report local civic issues with photo and location — routes them to the right municipal department.",
    tags: ["Next.js", "Azure Functions", "Cosmos DB"],
    status: "wip",
    gh: "https://github.com/shyamsinghnegi/CivicRelay",
    slot: "c",
    screenshots: [
      { alt: "Screenshot 1" },
      { alt: "Screenshot 2" },
      { alt: "Screenshot 3" },
    ],
    stack: [
      { layer: "Frontend", tech: "Next.js" },
      { layer: "API", tech: "Azure Functions" },
      { layer: "Database", tech: "Azure Cosmos DB" },
    ],
    features: [
      { title: "Photo + location reports", body: "Citizens snap a photo and drop a pin; the report is geotagged automatically." },
      { title: "Department routing", body: "Reports are routed to the correct municipal department based on category and location." },
    ],
    getStarted: [
      "Open the app and allow location access.",
      "Snap a photo of the issue and pick a category.",
      "Submit — the report is routed automatically.",
    ],
  },
]
